MAP = {
    "identifier": "urn:oasis:names:tc:SAML:2.0:attrname-format:uri",
    "to": {
        "specver": "https://data.gov.dk/model/core/specVersion",
        "bootstraptoken": "https://data.gov.dk/model/core/eid/bootstrapToken",
        "privilege": "https://data.gov.dk/model/core/eid/privilegesIntermediate",
        "levelofassurance": "https://data.gov.dk/concept/core/nsis/loa",
        "identityassurancelevel": "https://data.gov.dk/concept/core/nsis/ial",
        "authenticationassurancelevel": "https://data.gov.dk/concept/core/nsis/aal",
        "fullname": "https://data.gov.dk/model/core/eid/fullName",
        "firstname": "https://data.gov.dk/model/core/eid/firstName",
        "lastname": "https://data.gov.dk/model/core/eid/lastName",
        "alias": "https://data.gov.dk/model/core/eid/alias",
        "email": "https://data.gov.dk/model/core/eid/email",
        "age": "https://data.gov.dk/model/core/eid/age",
        "cpruuid": "https://data.gov.dk/model/core/eid/cprUuid",
        "cvr": "https://data.gov.dk/model/core/eid/professional/cvr",
        "cpr": "https://data.gov.dk/model/core/eid/cprNumber",
        "personname": "https://data.gov.dk/model/core/eid/fullName",
        "organizationname": "https://data.gov.dk/model/core/eid/professional/orgName",
    },
}
